### DISCUSSION TITLE
Initial Release – S3 Artifact Promotion Action v1.0.0

### DISCUSSION THREAD

**Discussion by grahamke** [grahamke/s3-artifact-promotion-action#1] [Announcements]
🚀 First public release of the S3 Artifact Promotion GitHub Action.

This action promotes a versioned deployment artifact to an S3 bucket, automatically archiving any existing "latest" artifact. It uses secure AWS OIDC authentication and assumes a role in your AWS account — no long-lived secrets required.

### ✨ Features

- ✅ Promote versioned artifact (e.g. `myapp-1.2.3.zip`) to `myapp/latest/`
- ✅ Automatically archive previous "latest" to `archive/myapp/latest/`
- ✅ AWS OIDC role assumption — no access keys required
- ✅ Written as a composite GitHub Action — no Docker dependencies

### 📦 Usage

```yaml
- name: Promote artifact
  uses: grahamke/s3-artifact-promotion-action@v1.0.0
  with:
    app_name: myapp
    version: 1.2.3
    artifact_path: lambda.zip
    bucket_name: ${{ vars.S3_BUCKET_NAME }}
    aws_region: ${{ secrets.AWS_REGION }}
    role_to_assume: ${{ secrets.AWS_ROLE_ARN }}
```
For more details, see the [README](https://github.com/grahamke/s3-artifact-promotion-action#readme).

<hr /><em>This discussion was created from the release <a href='https://github.com/grahamke/s3-artifact-promotion-action/releases/tag/v1.0.0'>Initial Release – S3 Artifact Promotion Action v1.0.0</a>.</em>
